// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MobileFixedMenu: typeof import('./components/navigation/MobileFixedMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectLanguage: typeof import('./components/navigation/SelectLanguage.vue')['default']
    TheHeader: typeof import('./components/navigation/TheHeader.vue')['default']
    TheMenu: typeof import('./components/navigation/TheMenu.vue')['default']
    TheNavigation: typeof import('./components/navigation/TheNavigation.vue')['default']
  }
}
