// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnnouncementView: typeof import('./components/home/announcement/AnnouncementView.vue')['default']
    MobileFixedMenu: typeof import('./components/navigation/MobileFixedMenu.vue')['default']
    ProjectView: typeof import('./components/home/project/ProjectView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectLanguage: typeof import('./components/navigation/SelectLanguage.vue')['default']
    TheAnnouncement: typeof import('./components/home/announcement/TheAnnouncement.vue')['default']
    TheHeader: typeof import('./components/navigation/TheHeader.vue')['default']
    TheLoader: typeof import('./components/TheLoader.vue')['default']
    TheMenu: typeof import('./components/navigation/TheMenu.vue')['default']
    TheNavigation: typeof import('./components/navigation/TheNavigation.vue')['default']
    TheProject: typeof import('./components/home/project/TheProject.vue')['default']
    TheTrending: typeof import('./components/home/trend/TheTrending.vue')['default']
    TrendingView: typeof import('./components/home/trend/TrendingView.vue')['default']
    WorkInProgress: typeof import('./components/WorkInProgress.vue')['default']
  }
}
